version: '2'
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"

  kafka1:
    image: confluent/kafka
    ports:
      - "9092:9092"   # kafka port
      - "11001:11000"
    links:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=Marios-MacBook-Pro.local
      - KAFKA_ADVERTISED_PORT=9092
      - JMX_PORT=11000


  kafka2:
    image: confluent/kafka
    ports:
      - "9093:9092"   # kafka port
      - "11002:11000"
    links:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_HOST_NAME=Marios-MacBook-Pro.local
      - KAFKA_ADVERTISED_PORT=9093
      - JMX_PORT=11000

  kafka3:
    image: confluent/kafka
    ports:
      - "9094:9092"   # kafka port
      - "11003:11000"
    links:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_HOST_NAME=Marios-MacBook-Pro.local
      - KAFKA_ADVERTISED_PORT=9094
      - JMX_PORT=11000

  kafka-manager:
    image: mzagar/kafka-manager-docker:1.3.3.4
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    environment:
      - ZK_HOSTS=zookeeper:2181
