spring:
  kafka:
    bootstrap-servers: localhost:9093,localhost:9094,localhost:9092
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      acks: all
      retries: 100
      batch-size: 951448

    consumer:
      group-id: SpringExampleConsumerGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

